### PR TITLE
Inject list.spr with client fixes

### PR DESCRIPTION
**Pull request by fgrep**
This will fix lancemaster poly without using any dll. The file zelgo.bin is the encoded list.spr

### CODE REVIEW

**Comment by fgrep** [comment]
If you want to know how decoded list.spr looks like
https://drive.google.com/file/d/0B9wC53nzlquPQURsUU5tVUpTMFU/view

**Comment by smith-j-travis** [comment]
I'm gonna have a chat with Soren before committing this. If he is on board with file updates, then I will create an update manager to write files to the users local system for bin updates, etc. If he isn't onboard of potentially adding new files or an auto update system, we may be SOL.

**Comment by vans163** [comment]
fgrep:  Any idea on how to interpret that data?  For example to replace annoying sprites like ToS flyers, dancing swords.

**Comment by fgrep** [comment]
@vans163 
It should be an easy task to simple replace a sprite. You can do that by replacing the sprite file itself (inside Sprite**.pak) or changing the list.spr to use another sprite for a given mob.

Check this list.spr used by old game clients: https://goo.gl/68uBgz
Drop me an email if u want more info or discuss about this. cesar dot fazan at gmail dot com

**Comment by smith-j-travis** [comment]
Soren has given the go-ahead on an updater system, so once I have that in place, we can add these modded bin files. This will also allow us to toggle the Win 10 bin for users automatically

**Comment by fgrep** [comment]
Thats nice.
Let me know if you want me to patch the .bin directly instead of using launcher to patch it.

Do you have the eat.exe? That program is used to pack files from Text/Sprite/Tile dirs into Text/Sprite/Tile.pak, this will be needed in case we want to update some npc dialog text for example.

I do have a decompiled C# unpacker for those pak files that can be used as a base to create a packer, let me know if you want it.

**Comment by smith-j-travis** [comment]
I do not have eat.exe, so that would definitely be cool if you could give it to me. If eat.exe is tried and true, then I don't see the need to use our own unpacker, but maybe in the future.

You don't hear about a lot of people having swing lag, but Soren did just make a post the other day about how to fix it, so at least *some* people still have the issue.

**Comment by fgrep** [comment]
Attached a patch for windowed mode on Windows 10, I can't send it as a pull request right now.
This patch set Windows registry key for 16Bit compatibility mode.

[WindowedMode-Win8+.zip](https://github.com/smith-j-travis/Launcher/files/75601/WindowedMode-Win8.zip)

**Comment by smith-j-travis** [comment]
Thanks for the patch!
Just letting you know I haven't forgotten about this. I'm just trying to fix my laptop so I can load up a Windows 10 VM for testing. Once I have that I will start committing changes again.

**Comment by smith-j-travis** [comment]
Just an FYI fgrep, the injection that was being done cause you to not be able to run 2 clients. login.dll must be doing something to allow this. For now I've left in the darkness injection, but reverted back to injecting login.dll itself to allow multiple clients.

**Comment by fgrep** [comment]
Just checked and it seems login.dll also patch to allow more than one client. I'm traveling for the next few weeks with just a crappy netbook so I'm not able to help that much now.
I will debug that when I get back. If you want to close this pull, I can open a new one when I get it working properly.

**Comment by smith-j-travis** [comment]
Thanks. I may close this pull since I've essentially integrated all of your fixes into my updater branch, however I've noticed one issue: the lancemaster injection doesn't work with the S3EP1U.bin file. Did you notice that as well or do you happen to know the injection point for that bin file from previous testing? If not, I guess I have a few weeks to get familiar with olly :)

**Comment by smith-j-travis** [comment]
Nevermind my last comment. There is no issue with Win10 other than my own stupidity... lancemaster is now 100% working on Win XP, Win 7 and Win 10... Haven't tested on Win 8 yet so thanks again for the patch! I'm going to close this now :)

**Pull request closed without merging**
